In [1]:
import pandas as pd

In [3]:
cox_study = pd.read_excel("Cox Study Phase.xlsx")
cox_test = pd.read_excel("Cox Test Phase.xlsx")

In [31]:
merged_df = pd.merge(cox_test, cox_study, on=['subject', 'stim.string.left', 'block', 'stim.num.left'], how='inner', left_index= False, right_index=False)

In [32]:
merged_df

,Unnamed: 0,subject,block,phase_x,condition_x,trial_x,stim.num.left,stim.num.right_x,stim.string.left,stim.string.right,...,study.partner.resp.num,study.partner.resp.string,recall.type,recall.list,condition.block,phase_y,condition_y,trial_y,stim.num.right_y,Target
0,142,2,3,test,Cued recall,1,339,0,FIRMLY,NaN,...,NaN,NaN,NaN,NaN,Cued recall 1,study,Cued recall,15,303,EXPANSION
1,143,2,3,test,Cued recall,2,282,0,ENJOYED,NaN,...,NaN,NaN,NaN,NaN,Cued recall 1,study,Cued recall,1,269,EFFECTIVELY
2,144,2,3,test,Cued recall,3,739,0,SERIOUSLY,NaN,...,NaN,NaN,Extralist intrusion,0.0,Cued recall 1,study,Cued recall,7,278,EMPLOYEES
3,145,2,3,test,Cued recall,4,576,0,PARTIES,NaN,...,576.0,PARTIES,Correct,3.0,Cued recall 1,study,Cued recall,2,74,BEDROOM
4,146,2,3,test,Cued recall,5,804,0,STOCK,NaN,...,NaN,NaN,NaN,NaN,Cued recall 1,study,Cued recall,13,396,HAVEN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27030,313000,462,6,test,Cued recall,16,387,0,GUN,NaN,...,NaN,NaN,Extralist intrusion,0.0,Cued recall 2,study,Cued recall,19,763,SISTERS
27031,313001,462,6,test,Cued recall,17,19,0,AFRICAN,NaN,...,NaN,NaN,NaN,NaN,Cued recall 2,study,Cued recall,11,89,BLOCKS
27032,313002,462,6,test,Cued recall,18,252,0,DOLLAR,NaN,...,NaN,NaN,Correct,6.0,Cued recall 2,study,Cued recall,13,272,ELECTION
27033,313003,462,6,test,Cued recall,19,639,0,PROPERTIES,NaN,...,NaN,NaN,NaN,NaN,Cued recall 2,study,Cued recall,2,210,CRYING
27034,313004,462,6,test,Cued recall,20,121,0,CARRIES,NaN,...,NaN,NaN,NaN,NaN,Cued recall 2,study,Cued recall,10,924,YOUTH

In [33]:
merged_df['stim.string.right'] = merged_df['Target']
merged_df.drop(columns=['Target'], inplace=True)

In [19]:
merged_df

,Unnamed: 0,subject,block,phase_x,condition_x,trial_x,stim.num.left,stim.num.right_x,stim.string.left,stim.string.right,...,resp.num,study.partner.resp.num,study.partner.resp.string,recall.type,recall.list,condition.block,phase_y,condition_y,trial_y,stim.num.right_y
0,142,2,3,test,Cued recall,1,339,0,FIRMLY,EXPANSION,...,NaN,NaN,NaN,NaN,NaN,Cued recall 1,study,Cued recall,15,303
1,143,2,3,test,Cued recall,2,282,0,ENJOYED,EFFECTIVELY,...,NaN,NaN,NaN,NaN,NaN,Cued recall 1,study,Cued recall,1,269
2,144,2,3,test,Cued recall,3,739,0,SERIOUSLY,EMPLOYEES,...,NaN,NaN,NaN,Extralist intrusion,0.0,Cued recall 1,study,Cued recall,7,278
3,145,2,3,test,Cued recall,4,576,0,PARTIES,BEDROOM,...,74.0,576.0,PARTIES,Correct,3.0,Cued recall 1,study,Cued recall,2,74
4,146,2,3,test,Cued recall,5,804,0,STOCK,HAVEN,...,NaN,NaN,NaN,NaN,NaN,Cued recall 1,study,Cued recall,13,396
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27030,313000,462,6,test,Cued recall,16,387,0,GUN,SISTERS,...,NaN,NaN,NaN,Extralist intrusion,0.0,Cued recall 2,study,Cued recall,19,763
27031,313001,462,6,test,Cued recall,17,19,0,AFRICAN,BLOCKS,...,NaN,NaN,NaN,NaN,NaN,Cued recall 2,study,Cued recall,11,89
27032,313002,462,6,test,Cued recall,18,252,0,DOLLAR,ELECTION,...,NaN,NaN,NaN,Correct,6.0,Cued recall 2,study,Cued recall,13,272
27033,313003,462,6,test,Cued recall,19,639,0,PROPERTIES,CRYING,...,NaN,NaN,NaN,NaN,NaN,Cued recall 2,study,Cued recall,2,210
27034,313004,462,6,test,Cued recall,20,121,0,CARRIES,YOUTH,...,NaN,NaN,NaN,NaN,NaN,Cued recall 2,study,Cued recall,10,924

In [20]:
merged_df.columns

Index(['Unnamed: 0', 'subject', 'block', 'phase_x', 'condition_x', 'trial_x',
       'stim.num.left', 'stim.num.right_x', 'stim.string.left',
       'stim.string.right', 'stim.distractor', 'studied', 'freq.left',
       'cv.left', 'old.left', 'freq.right', 'cv.right', 'old.right', 'rt',
       'distractor.resp', 'resp', 'resp.string', 'resp.type',
       'resp.type.rescore', 'study.pos.left', 'study.pos.right', 'kf.left',
       'kf.right', 'resp.string.corr', 'study.partner.left.num',
       'study.partner.right.num', 'study.partner.left.string',
       'study.partner.right.string', 'resp.num', 'study.partner.resp.num',
       'study.partner.resp.string', 'recall.type', 'recall.list',
       'condition.block', 'phase_y', 'condition_y', 'trial_y',
       'stim.num.right_y'],
      dtype='object')

In [34]:
merged_df.drop(columns=['Unnamed: 0', 'condition_y', 'phase_y', 'trial_y'], inplace=True)

In [35]:
merged_df.rename(columns={'condition_x': 'condition', 'phase_x': 'phase', 'trial_x' : 'trial'}, inplace=True)

In [23]:
merged_df

,subject,block,phase,condition,trial,stim.num.left,stim.num.right_x,stim.string.left,stim.string.right,stim.distractor,...,study.partner.right.num,study.partner.left.string,study.partner.right.string,resp.num,study.partner.resp.num,study.partner.resp.string,recall.type,recall.list,condition.block,stim.num.right_y
0,2,3,test,Cued recall,1,339,0,FIRMLY,EXPANSION,0,...,NaN,EXPANSION,NaN,NaN,NaN,NaN,NaN,NaN,Cued recall 1,303
1,2,3,test,Cued recall,2,282,0,ENJOYED,EFFECTIVELY,0,...,NaN,EFFECTIVELY,NaN,NaN,NaN,NaN,NaN,NaN,Cued recall 1,269
2,2,3,test,Cued recall,3,739,0,SERIOUSLY,EMPLOYEES,0,...,NaN,EMPLOYEES,NaN,NaN,NaN,NaN,Extralist intrusion,0.0,Cued recall 1,278
3,2,3,test,Cued recall,4,576,0,PARTIES,BEDROOM,0,...,NaN,BEDROOM,NaN,74.0,576.0,PARTIES,Correct,3.0,Cued recall 1,74
4,2,3,test,Cued recall,5,804,0,STOCK,HAVEN,0,...,NaN,HAVEN,NaN,NaN,NaN,NaN,NaN,NaN,Cued recall 1,396
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27030,462,6,test,Cued recall,16,387,0,GUN,SISTERS,0,...,NaN,SISTERS,NaN,NaN,NaN,NaN,Extralist intrusion,0.0,Cued recall 2,763
27031,462,6,test,Cued recall,17,19,0,AFRICAN,BLOCKS,0,...,NaN,BLOCKS,NaN,NaN,NaN,NaN,NaN,NaN,Cued recall 2,89
27032,462,6,test,Cued recall,18,252,0,DOLLAR,ELECTION,0,...,NaN,ELECTION,NaN,NaN,NaN,NaN,Correct,6.0,Cued recall 2,272
27033,462,6,test,Cued recall,19,639,0,PROPERTIES,CRYING,0,...,NaN,CRYING,NaN,NaN,NaN,NaN,NaN,NaN,Cued recall 2,210
27034,462,6,test,Cued recall,20,121,0,CARRIES,YOUTH,0,...,NaN,YOUTH,NaN,NaN,NaN,NaN,NaN,NaN,Cued recall 2,924

In [36]:
merged_df['resp.type.rescore']

0        Miss
1        Miss
2          FA
3         Hit
4        Miss
         ...
27030      FA
27031    Miss
27032     Hit
27033    Miss
27034    Miss
Name: resp.type.rescore, Length: 27035, dtype: object

In [37]:
merged_df['stim.num.right_x'] = merged_df['stim.num.right_y']
merged_df.rename(columns={'stim.num.right_x': 'stim.num.right'}, inplace=True)

In [38]:
merged_df.drop(columns=['cv.left', 'cv.right', 'distractor.resp', 'freq.left', 'freq.right',
       'old.left', 'old.right', 'resp', 'rt', 'stim.distractor',
       'stim.num.right_y', 'studied'], inplace=True)

In [39]:
merged_df

,subject,block,phase,condition,trial,stim.num.left,stim.num.right,stim.string.left,stim.string.right,resp.string,...,study.partner.left.num,study.partner.right.num,study.partner.left.string,study.partner.right.string,resp.num,study.partner.resp.num,study.partner.resp.string,recall.type,recall.list,condition.block
0,2,3,test,Cued recall,1,339,303,FIRMLY,EXPANSION,NaN,...,303,NaN,EXPANSION,NaN,NaN,NaN,NaN,NaN,NaN,Cued recall 1
1,2,3,test,Cued recall,2,282,269,ENJOYED,EFFECTIVELY,NaN,...,269,NaN,EFFECTIVELY,NaN,NaN,NaN,NaN,NaN,NaN,Cued recall 1
2,2,3,test,Cued recall,3,739,278,SERIOUSLY,EMPLOYEES,tough,...,278,NaN,EMPLOYEES,NaN,NaN,NaN,NaN,Extralist intrusion,0.0,Cued recall 1
3,2,3,test,Cued recall,4,576,74,PARTIES,BEDROOM,bedroom,...,74,NaN,BEDROOM,NaN,74.0,576.0,PARTIES,Correct,3.0,Cued recall 1
4,2,3,test,Cued recall,5,804,396,STOCK,HAVEN,NaN,...,396,NaN,HAVEN,NaN,NaN,NaN,NaN,NaN,NaN,Cued recall 1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27030,462,6,test,Cued recall,16,387,763,GUN,SISTERS,Female,...,763,NaN,SISTERS,NaN,NaN,NaN,NaN,Extralist intrusion,0.0,Cued recall 2
27031,462,6,test,Cued recall,17,19,89,AFRICAN,BLOCKS,NaN,...,89,NaN,BLOCKS,NaN,NaN,NaN,NaN,NaN,NaN,Cued recall 2
27032,462,6,test,Cued recall,18,252,272,DOLLAR,ELECTION,Election,...,272,NaN,ELECTION,NaN,NaN,NaN,NaN,Correct,6.0,Cued recall 2
27033,462,6,test,Cued recall,19,639,210,PROPERTIES,CRYING,NaN,...,210,NaN,CRYING,NaN,NaN,NaN,NaN,NaN,NaN,Cued recall 2
27034,462,6,test,Cued recall,20,121,924,CARRIES,YOUTH,NaN,...,924,NaN,YOUTH,NaN,NaN,NaN,NaN,NaN,NaN,Cued recall 2

In [41]:
merged_df.to_excel("Cox Data Final.xlsx", index=False)